### ISSUE TITLE
Will you publish the code?

### ISSUE THREAD

**Issue by finngaida** [ilovepose/DarkPose#1]
In the paper you mention a "model-agnostic plugin" - will you open source the code for your approach?

**Comment by djangogo** [comment]
yes, we will

**Comment by djangogo** [comment]
yes, we will

**Comment by finngaida** [comment]
Do you have a rough estimate of when that will be? :)

**Comment by bhyzhao** [comment]
@djangogo When?

**Comment by djangogo** [comment]
@finngaida @bhyzhao 
Hi, the code is released now.

**Comment by dmitrysarov** [comment]
Will you release pre-trained models?
