### ISSUE TITLE
Where are pretrained weights of the best model?

### ISSUE THREAD

**Issue by hongsukchoi** [ilovepose/DarkPose#13]
Hi, thanks for your great work.

At README.md, there's an evaluation result of HRNet+Dark trained on MSCOCO+__AI Challenger__ with some other techniques. (Indicated with *-+)
Where can I found the pretrained weights of this best performing model? I can't find it on the link you provided
<img width="1087" alt="스크린샷 2020-09-09 18 09 35" src="https://user-images.githubusercontent.com/31090011/92579330-05a06480-f2c8-11ea-85ee-6638310aa4e8.png">

Thanks in advance.

**Comment by djangogo** [comment]
The model is not provided.

**Comment by hongsukchoi** [comment]
Do you have any plan to release the model? 
I think many people would like to use the best model.
