### ISSUE TITLE
I have a quesetion for the code

### ISSUE THREAD

**Issue by aidarikako** [ilovepose/DarkPose#14]
DarkPose/lib/dataset/JointsDataset.py /line 284-286
        `feat_stride = self.image_size / self.heatmap_size`
        `mu_x = joint[0]`
        `mu_y = joint[1]`
I have a question that why the code is not as follow:
        `feat_stride = self.image_size / self.heatmap_size`
        `mu_x = joint[0]/feat_stride[0]`
        `mu_y = joint[1]/feat_stride[1]`

And I search the JointsDataset.py, I find that you don't use the 'feat_stride' in anywhere, but if your heatmap is 1/4 downsampling of the ori-image, I think it's a neccecery step to use the 'feat_stride'.

I want to know if my understanding is wrong or the code is wrong, thanks.

**Comment by djangogo** [comment]
we already commented the following line.
`feat_stride = self.image_size / self.heatmap_size`

**Comment by EEWenbinWu** [comment]
> DarkPose/lib/dataset/JointsDataset.py /line 284-286
> `feat_stride = self.image_size / self.heatmap_size`
> `mu_x = joint[0]`
> `mu_y = joint[1]`
> I have a question that why the code is not as follow:
> `feat_stride = self.image_size / self.heatmap_size`
> `mu_x = joint[0]/feat_stride[0]`
> `mu_y = joint[1]/feat_stride[1]`
> 
> And I search the JointsDataset.py, I find that you don't use the 'feat_stride' in anywhere, but if your heatmap is 1/4 downsampling of the ori-image, I think it's a neccecery step to use the 'feat_stride'.
> 
> I want to know if my understanding is wrong or the code is wrong, thanks.

I think that your understanding is right

**Comment by HeathHose** [comment]
Please refer to **Coordinate Encoding** in Paper, and check this code block:

https://github.com/ilovepose/DarkPose/blob/612fad594eddd022b8a162a2c7274f9ee8d06d2c/lib/dataset/JointsDataset.py#L181-L184

**Comment by EEWenbinWu** [comment]
> Please refer to **Coordinate Encoding** in Paper, and check this code block:
> 
> https://github.com/ilovepose/DarkPose/blob/612fad594eddd022b8a162a2c7274f9ee8d06d2c/lib/dataset/JointsDataset.py#L181-L184

I know，but the heatmap was wrong because the x, y  are larger than 72 and 96

**Comment by HeathHose** [comment]
> > Please refer to **Coordinate Encoding** in Paper, and check this code block:
> > https://github.com/ilovepose/DarkPose/blob/612fad594eddd022b8a162a2c7274f9ee8d06d2c/lib/dataset/JointsDataset.py#L181-L184
> 
> I know，but the heatmap was wrong because the x, y are larger than 72 and 96

joints_heatmap has been affined to the heatmap space and the x, y is (72, 96).   You can compare the differences  between darkpose and hrnet in affine_transform

**Comment by EEWenbinWu** [comment]
Thank you, it's my problem.
