### ISSUE TITLE
How to test the model on COCO test-dev set 2017

### ISSUE THREAD

**Issue by Ozone-oo** [ilovepose/DarkPose#15]
I want to test model on test-dev set, but the code tool/test.py is only for testing on validation set (5000 images):

So, I have a question: How to test the model on COCO test-dev set 2017 to submit the json file to codalab server?
I'm looking forward from you. Thank you for your great work!

**Comment by hbin-ac** [comment]
1、Download the test2017 dataset and image info.
2、Download the detection result on [test-dev2017.](https://onedrive.live.com/?authkey=%21AKqtqKs162Z5W7g&id=56B9F9C97F261712%2110694&cid=56B9F9C97F261712)
3、Modify the yaml as follow
**DATASET:
  TRAIN_SET: 'test-dev2017'
TEST:
  COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_test-dev2017_detections_AP_H_609_person.json'
  USE_GT_BBOX: false**

**Comment by hbin-ac** [comment]
1、Download the test2017 dataset and image info.
2、Download the detection result on [test-dev2017.](https://onedrive.live.com/?authkey=%21AKqtqKs162Z5W7g&id=56B9F9C97F261712%2110694&cid=56B9F9C97F261712)
3、Modify the yaml file as follow
**DATASET:
TRAIN_SET: 'test-dev2017'
TEST:
COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_test-dev2017_detections_AP_H_609_person.json'
USE_GT_BBOX: false**

**Comment by hbin-ac** [comment]
1、Download the test2017 dataset and image info.
2、Download the detection result on [test-dev2017.](https://onedrive.live.com/?authkey=%21AKqtqKs162Z5W7g&id=56B9F9C97F261712%2110694&cid=56B9F9C97F261712)
3、Modify the yaml file as follow
**DATASET:
TEST_SET: 'test-dev2017'
TEST:
COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_test-dev2017_detections_AP_H_609_person.json'
USE_GT_BBOX: false**

**Comment by Ozone-oo** [comment]
> 1、Download the test2017 dataset and image info.
> 2、Download the detection result on [test-dev2017.](https://onedrive.live.com/?authkey=%21AKqtqKs162Z5W7g&id=56B9F9C97F261712%2110694&cid=56B9F9C97F261712)
> 3、Modify the yaml file as follow
> **DATASET: TEST_SET: 'test-dev2017' TEST: COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_test-dev2017_detections_AP_H_609_person.json' USE_GT_BBOX: false**

Thank you！！！
