### ISSUE TITLE
AI challenger dataset is not accessible. How to reproduce your result of W48*? 

### ISSUE THREAD

**Issue by ShuangjunLiu** [ilovepose/DarkPose#18]
I can't download the AI challenger data.  (https://challenger.ai/dataset/keypoint)
How do you get the result for HRnet W48 *  ( with extra data?)

**Comment by hbin-ac** [comment]
You can download AI challenger dataset at [code:55py ](https://pan.baidu.com/s/1GK-gNdOm2YJBkGw0xxgrdA)
