### ISSUE TITLE
Explanation for COCO data filtering

### ISSUE THREAD

**Issue by mrronchi** [ilovepose/DarkPose#19]
It seems from your [code](https://github.com/ilovepose/DarkPose/blob/612fad594eddd022b8a162a2c7274f9ee8d06d2c/lib/dataset/JointsDataset.py#L230) that you are selectively discarding some annotations. If I understand correctly you look at the center of all the visible keypoints and the center of the bounding box annotation and measure the ks between these two points.

However it is not clear how you selected the values to measure this heuristic. In particular:
- How did you decide 0.2 in `ks = np.exp(-1.0*(diff_norm2**2) / ((0.2)**2*2.0*area))`
- What does the computed `metric = (0.2 / 16) * num_vis + 0.45 - 0.2 / 16` correspond to and what does the number 0.45 represent?

Thanks a lot! Great work!

**Comment by djangogo** [comment]
@mrronchi 
Hi，you can ask the author of HRNet.
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/
