### ISSUE TITLE
The difference in Table 1 and Table 2 ?

### ISSUE THREAD

**Issue by LightToYang** [ilovepose/DarkPose#2]
![image](https://user-images.githubusercontent.com/17929130/72231573-30ca9b00-35f7-11ea-91d9-196b8cac0fff.png)

**Comment by djangogo** [comment]
@LightToYang 
Hi,  
The result you pointed out in Table2 is the model trained using biased heatmap
and for this model we use our decoding method

The result you pointed out in Table3 is the model trained using biased heatmap
and for this model we use the standard decoding method
