### ISSUE TITLE
Flip test shifting?

### ISSUE THREAD

**Issue by fourierer** [ilovepose/DarkPose#23]
Sorry to bother you, I have a little question. In HRNet or SimpleBaseline, flip strategy is often used in test process,  there is often 1 pixel shifting in flip output. But in your code, I didn't fine the shifting process, could you tell me the reason?
![1](https://user-images.githubusercontent.com/55837279/99525396-b87df480-29d4-11eb-83a7-bc16ed8282cd.png)

**Comment by hbin-ac** [comment]
DARK uses unbiased heatmap encoding, this process involves unbiased data processing.

**Comment by hbin-ac** [comment]
DARK uses unbiased heatmap encoding, this process involves unbiased data processing. So there is no error and no manual shifting is required.

**Comment by fourierer** [comment]
Thank you so much for your reply~
