### ISSUE TITLE
Could you explain how to calculate the second derivative 'dxy' ?

### ISSUE THREAD

**Issue by seekFire** [ilovepose/DarkPose#25]
In inference.py, function **taylor**, the 2nd derivative `dxy` is calculated by:

`dxy = 0.25 * (hm[py+1][px+1] - hm[py-1][px+1] - hm[py+1][px-1]  + hm[py-1][px-1])`

So could you explain why is the equation like this?

**Comment by bigbrother33** [comment]
same question - -

**Comment by hbin-ac** [comment]
dx[px, py] = (hm[px+1, py] - hm[px -1, py]) / 2
dxy[px, py] = (dx[px, py+1] - dx[px, py-1]) / 2 = (hm[py+1, px+1] - hm[py-1, px+1] - hm[py+1, px-1] + hm[py-1, px-1]) / 4

**Comment by seekFire** [comment]
@hbin-ac You're so smart! Thank you very much!
