### ISSUE TITLE
Question about a small detail

### ISSUE THREAD

**Issue by seekFire** [ilovepose/DarkPose#26]
In evaluate.py, function **calc_dists**, the Euclidean distance will be calculated under the condition:

`if target[n, c, 0] > 1 and target[n, c, 1] > 1:`

It seems that you exclude the case where the target coordinates are in [0, 1], so why do this?

**Comment by seekFire** [comment]
I think you may aim to preserve the groundtruth coordinates when carry on one pixel shifting of flip testing. Is it right?

**Comment by djangogo** [comment]
@seekFire
You may need to ask the author of HRNet
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/
