### ISSUE TITLE
code for 'standard coordinate decoding method'

### ISSUE THREAD

**Issue by nyanye** [ilovepose/DarkPose#29]
Thanks for the great paper, can I get the code for standard coordinate decoding method that you used for Table 1 to reproduce the comparison?
![image](https://user-images.githubusercontent.com/21135812/110725290-b3ca9e00-825a-11eb-8da8-02367b7bd397.png)
![image](https://user-images.githubusercontent.com/21135812/110725366-d78de400-825a-11eb-8187-f0f952356751.png)

**Comment by djangogo** [comment]
Hi,@nyanye 
As for the standard decoding and encoding,
you can use the original HRNet repo.
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/
Thanks
