### ISSUE TITLE
code

### ISSUE THREAD

**Issue by change-v8** [ilovepose/DarkPose#3]
excuse me ,i am a begonner of cs ,i want to know when will you show your code ,sorry to disturb you

**Comment by jialee93** [comment]
+1, looking forward to the interesting work.

**Comment by antithing** [comment]
+ another 1! Thanks!

**Comment by biras11** [comment]
Any news about the code release?

**Comment by winggo12** [comment]
Hello, would you mind sharing the code to us? Thank you very much.

**Comment by andres-fr** [comment]
Hi guys! First of all thanks a lot for the contribution.

I made an implementation, on a first qualitative look seems to be alright, but any feedback is welcome: https://aferro.dynu.net/blog/dark_heatmap_decoding/

Cheers!  
Andres

**Comment by djangogo** [comment]
@andres-fr @antithing @hellojialee @winggo12 @change-v8 
Hi, our code is released
