### ISSUE TITLE
AP, AR on MPII Dataset

### ISSUE THREAD

**Issue by badri2304** [ilovepose/DarkPose#31]
I am currently working on extending the OKS similarity metric to MPII dataset, haven't finished it yet so, I am unaware of the problems but for now I haven't faced any. However, I wonder why none of the papers submit AP, AR on MPII dataset?

why does everyone use PCK for MPII dataset, AP for COCO? Is there any particular reason??

Also, If someone has already implemented can you share in this thread?

Thanks.

**Comment by xizero00** [comment]
Hi, The logic is:
If you want to compare with these models evaluated on MPII, you have to use the PCK metric.
This is the reason.
