### ISSUE TITLE
why are there two coefficients(0.5, 0.25) before the derivative and hessian?

### ISSUE THREAD

**Issue by SemonWang** [ilovepose/DarkPose#38]
https://github.com/ilovepose/DarkPose/blob/0185b427f34a08d93ea7e948ccc3e7fdc78d88c5/lib/core/inference.py#L51

According to the taylor series, the offset is equal to -InvH * g. While in this code, the offset is equal to  -2*InvH * g because of the two coefficients. Can you please explain it?

**Comment by APORduo** [comment]
I think the coefficients are induced by the caculation of gradients, and for details you can refer to #25 .

**Comment by SemonWang** [comment]
> 

got it! Thank you very much!
