### ISSUE TITLE
Unable to reproduce the score presented as Model + Dark

### ISSUE THREAD

**Issue by tabbas97** [ilovepose/DarkPose#4]
Hi,

I ran the test.py with the default HRNet w32 256 x 192 and HRNet w32 384 x 288. I am able to only reproduce the author's scores of 74.4 and 75.8 respectively. 

Command Used : 
`python tools/test.py --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml TEST.MODEL_FILE <MODEL_PATH> TEST.USE_GT_BBOX False`

The MODEL_FILE used was the original author's model.

and likewise for 384 x 288.

I observed that the function taylor(hm, coord) in lib/core/inference.py was being invoked but I am not able to reproduce the results provided by you.

What do I need to to do reproduce the results provided ?

Thanks in advance

**Comment by djangogo** [comment]
You have to re-train the model to reproduce the results.

**Comment by tabbas97** [comment]
Apologies. and Thanks.

I understood it in a different light. You have any timeline in mind for when you would be releasing the models ?

**Comment by djangogo** [comment]
Due to the reason that I have graduated from the university,  
I do not have access to the GPU server for now.

**Comment by StephenGreat** [comment]
@tabbas97 Could you share the address for downloading pretrained model file?
