### ISSUE TITLE
if flip test is not used, Dark is not helpful for performance

### ISSUE THREAD

**Issue by Marshall0304** [ilovepose/DarkPose#5]
Did you have test the performance of Dark if the flip test is not used? It seems that we should use flip test and Dark or standard shifting together, but you didn't mention that in your paper nor did HRNet.

**Comment by djangogo** [comment]
No, we did not test it when the flip test is not used.
Do you re-train the model? or just use the official HRNet's model to evaluate DARK?
Could you please provide the results?

**Comment by Marshall0304** [comment]
> No, we did not test it when the flip test is not used.
> I think it's very interesting to evaluate DARK when the flip test is not used.
> 
> Do you re-train the model? or just use the official HRNet's model to evaluate DARK?

I used my own model (a lightweight top-down half body model) with DARK as the paper said it's a model-agnostic plugin. And i just used DARK in the inference phase. So, to be exact, i just evaluate the decoding module of DARK in my own dataset (a half body dataset).
But, according to the Table 3 in your paper, the decoding module can get 1.5% boost.  Maybe i should add filp test and see what can i get.
