### ISSUE TITLE
How to download pretrained model for test?

### ISSUE THREAD

**Issue by StephenGreat** [ilovepose/DarkPose#8]
Hi, I am new to DarkPose. Is there any address for downloading pretrained model file?

**Comment by kapoorparul** [comment]
same query.

**Comment by superWSL** [comment]
I used the pre-trained model in HRNet, but the result is the same as the result without DARK. I don’t know why

**Comment by djangogo** [comment]
Hi, @kapoorparul @StephenGreat @superWSL @
the pretrained [models](https://drive.google.com/drive/folders/14kAA1zXuKODYgrRiQmKnVcipbY7RedVV?usp=sharing) can be downloadable now.

**Comment by kapoorparul** [comment]
> Hi, @kapoorparul @StephenGreat @superWSL @
> the pretrained [models](https://drive.google.com/drive/folders/14kAA1zXuKODYgrRiQmKnVcipbY7RedVV?usp=sharing) can be downloaded now.
Can we expect hand pose estimation also?
