### ISSUE TITLE
Why the test result on HRNet with DarkPose is the same as the result without DARK?

### ISSUE THREAD

**Issue by superWSL** [ilovepose/DarkPose#9]
Run with DarkPose's open source code. The test result on HRNet is the same as the result without DARK. There is no improvement. What is the reason? The configuration file and pre-training model are all used in HRNet.

**Comment by djangogo** [comment]
You should use the [models](https://drive.google.com/drive/folders/14kAA1zXuKODYgrRiQmKnVcipbY7RedVV?usp=sharing) we provided.

**Comment by superWSL** [comment]
> The reason is that there are some other modifications in our source code.
> If you use the original HRNet model provided by MSRA, these modifications will cancel the improvement from
> the DARK.
> 
> If you want to get the results for our DARK method, you should use the [models](https://drive.google.com/drive/folders/14kAA1zXuKODYgrRiQmKnVcipbY7RedVV?usp=sharing) we provided.
> If you want to evaluate the effect of the decoding part(our taylor method), you should copy
> [the taylor function](https://github.com/ilovepose/DarkPose/blob/master/lib/core/inference.py#L51)
> to the original source code of HRNet and then use the model provided by MSRA.

Thank you for your answer, I have received the pre-trained model you provided, and the test results are the same as those in the paper.

**Comment by superWSL** [comment]
Thank you, I have received the model you provided, and the test results are the same as those in the paper！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ilovepose/DarkPose"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午3:51
收件人:&nbsp;"ilovepose/DarkPose"<DarkPose@noreply.github.com&gt;;
抄送:&nbsp;"FORGET"<1445934720@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ilovepose/DarkPose] Why the test result on HRNet with DarkPose is the same as the result without DARK? (#9)





 
You should use the models we provided.

**Comment by seekFire** [comment]
@djangogo Hello! I wonder that what modification have you done to the original MSRA HRNet?

**Comment by djangogo** [comment]
> @djangogo Hello! I wonder that what modification have you done to the original MSRA HRNet?
You can use the diff tool to see the modifications

**Comment by seekFire** [comment]
@djangogo Thank you! I took a roughly look at your code & official code by using vimdiff, I found the modification you did mainly focus on several aspects as follows:
1. set **relu** to inplace=True;
2. set some input channel to fixed value;
3. change the upsampling mode from **bilinear** to **nearest**;
4. move the interpolate operation from function **get_num_inchannels** to the function **_make_fuse_layers**;

And maybe I haven't noticed the other significant modification... But according to the opinion you mentioned:

> If you use the original HRNet model provided by MSRA, these modifications will cancel the improvement from
> the DARK.

Can I understand that your modified model doesn't perform as well as MSRA official model?
